-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 09:52:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Instrument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Instrument` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Instrument` (
  `idInstrument` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstrument`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`localite` ;

CREATE TABLE IF NOT EXISTS `mydb`.`localite` (
  `idlocalite` INT NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `pays` VARCHAR(45) NOT NULL,
  `codePostale` CHAR(5) NOT NULL,
  PRIMARY KEY (`idlocalite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `rue1` VARCHAR(45) NOT NULL,
  `rue2` VARCHAR(45) NULL,
  `complement` VARCHAR(255) NULL,
  `fk_localite` INT NOT NULL,
  PRIMARY KEY (`idAdresse`),
  INDEX `fk_villeAdresse_idx` (`fk_localite` ASC),
  CONSTRAINT `fk_villeAdresse`
    FOREIGN KEY (`fk_localite`)
    REFERENCES `mydb`.`localite` (`idlocalite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Groupe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Groupe` (
  `idgroupe` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgroupe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Membre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Membre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Membre` (
  `idMembre` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `dateNaissance` DATETIME NOT NULL,
  `telephone` VARCHAR(20) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `motDePasse` VARCHAR(45) NOT NULL,
  `fk_instrument` INT NULL,
  `fk_adresse` INT NOT NULL,
  `fk_groupe` INT NOT NULL,
  PRIMARY KEY (`idMembre`, `mail`),
  INDEX `fk_instrumentMembre_idx` (`fk_instrument` ASC),
  INDEX `fk_adresseMembre_idx` (`fk_adresse` ASC),
  INDEX `fk_typeUtilisateur_idx` (`fk_groupe` ASC),
  CONSTRAINT `fk_instrumentMembre`
    FOREIGN KEY (`fk_instrument`)
    REFERENCES `mydb`.`Instrument` (`idInstrument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adresseMembre`
    FOREIGN KEY (`fk_adresse`)
    REFERENCES `mydb`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_typeUtilisateur`
    FOREIGN KEY (`fk_groupe`)
    REFERENCES `mydb`.`Groupe` (`idgroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypeEvenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TypeEvenement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TypeEvenement` (
  `idType` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReferentExterieur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ReferentExterieur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ReferentExterieur` (
  `idreferentExterieur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(20) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idreferentExterieur`, `mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evenement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evenement` (
  `idEvenement` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `dateDebut` DATETIME NOT NULL,
  `dateFin` DATETIME NOT NULL,
  `cachet` FLOAT NULL,
  `description` MEDIUMTEXT NULL,
  `image` VARCHAR(255) NULL,
  `valider` TINYINT NOT NULL,
  `fk_adresse` INT NOT NULL,
  `fk_type` INT NOT NULL,
  `fk_membre` INT NOT NULL,
  `fk_referentExterieur` INT NULL,
  PRIMARY KEY (`idEvenement`),
  INDEX `fk_adresseEvenement_idx` (`fk_adresse` ASC),
  INDEX `fk_typeEvenement_idx` (`fk_type` ASC),
  INDEX `fk_referentExterieur_idx` (`fk_referentExterieur` ASC),
  INDEX `fk_membre_idx` (`fk_membre` ASC),
  CONSTRAINT `fk_adresseEvenement`
    FOREIGN KEY (`fk_adresse`)
    REFERENCES `mydb`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_typeEvenement`
    FOREIGN KEY (`fk_type`)
    REFERENCES `mydb`.`TypeEvenement` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_referentExterieur`
    FOREIGN KEY (`fk_referentExterieur`)
    REFERENCES `mydb`.`ReferentExterieur` (`idreferentExterieur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membre`
    FOREIGN KEY (`fk_membre`)
    REFERENCES `mydb`.`Membre` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reponse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reponse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reponse` (
  `idReponse` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`idReponse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Participant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Participant` (
  `fk_reponce` INT NOT NULL,
  `fk_membre` INT NOT NULL,
  `fk_evenement` INT NOT NULL,
  INDEX `fk_membresParticipant_idx` (`fk_membre` ASC),
  INDEX `fk_evenementParticipant_idx` (`fk_evenement` ASC),
  INDEX `fk_reponceParticipant_idx` (`fk_reponce` ASC),
  CONSTRAINT `fk_membresParticipant`
    FOREIGN KEY (`fk_membre`)
    REFERENCES `mydb`.`Membre` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evenementParticipant`
    FOREIGN KEY (`fk_evenement`)
    REFERENCES `mydb`.`Evenement` (`idEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponceParticipant`
    FOREIGN KEY (`fk_reponce`)
    REFERENCES `mydb`.`Reponse` (`idReponse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmploiDuTemps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EmploiDuTemps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EmploiDuTemps` (
  `idEmploiDuTemps` INT NOT NULL AUTO_INCREMENT,
  `EmploiDuTempscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmploiDuTemps`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GroupeRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GroupeRole` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GroupeRole` (
  `fk_groupe` INT NOT NULL,
  `fk_role` INT NOT NULL,
  INDEX `fk_groupe_idx` (`fk_groupe` ASC),
  INDEX `fk_role_idx` (`fk_role` ASC),
  CONSTRAINT `fk_groupe`
    FOREIGN KEY (`fk_groupe`)
    REFERENCES `mydb`.`Groupe` (`idgroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role`
    FOREIGN KEY (`fk_role`)
    REFERENCES `mydb`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actualite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Actualite` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Actualite` (
  `idActualite` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `image` VARCHAR(255) NULL,
  `description` MEDIUMTEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `fk_membre` INT NOT NULL,
  PRIMARY KEY (`idActualite`),
  CONSTRAINT `fk_membre_constraint`
    FOREIGN KEY (`fk_membre`)
    REFERENCES `mydb`.`Membre` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MembreRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MembreRole` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MembreRole` (
  `fk_membre` INT NOT NULL,
  `fk_role` INT NOT NULL,
  INDEX `fk_membre_idx` (`fk_membre` ASC),
  INDEX `fk_Role_idx` (`fk_role` ASC),
  CONSTRAINT `fk_membre_constraint`
    FOREIGN KEY (`fk_membre`)
    REFERENCES `mydb`.`Membre` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role`
    FOREIGN KEY (`fk_role`)
    REFERENCES `mydb`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
