-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 10:24:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBBagaD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBBagaD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBBagaD` DEFAULT CHARACTER SET utf8 ;
USE `DBBagaD` ;

-- -----------------------------------------------------
-- Table `DBBagaD`.`Instrument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`Instrument` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`Instrument` (
  `idInstrument` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstrument`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`localite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`Localite` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`Localite` (
  `idlocalite` INT NOT NULL AUTO_INCREMENT,
  `ville` VARCHAR(45) NOT NULL,
  `pays` VARCHAR(45) NOT NULL,
  `codePostale` CHAR(5) NOT NULL,
  PRIMARY KEY (`idlocalite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `rue1` VARCHAR(45) NOT NULL,
  `rue2` VARCHAR(45) NULL,
  `complement` VARCHAR(255) NULL,
  `fk_localite` INT NOT NULL,
  PRIMARY KEY (`idAdresse`),
  INDEX `fk_villeAdresse_idx` (`fk_localite` ASC),
  CONSTRAINT `fk_localiteAdresse`
    FOREIGN KEY (`fk_localite`)
    REFERENCES `DBBagaD`.`localite` (`idlocalite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`Groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`Groupe` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`Groupe` (
  `idgroupe` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgroupe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`Membre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`Membre` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`Membre` (
  `idMembre` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `dateNaissance` DATETIME NOT NULL,
  `telephone` VARCHAR(20) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `motDePasse` VARCHAR(45) NOT NULL,
  `fk_instrument` INT NULL,
  `fk_adresse` INT NOT NULL,
  `fk_groupe` INT NOT NULL,
  PRIMARY KEY (`idMembre`, `mail`),
  INDEX `fk_instrumentMembre_idx` (`fk_instrument` ASC),
  INDEX `fk_adresseMembre_idx` (`fk_adresse` ASC),
  INDEX `fk_typeUtilisateur_idx` (`fk_groupe` ASC),
  CONSTRAINT `fk_instrumentMembre`
    FOREIGN KEY (`fk_instrument`)
    REFERENCES `DBBagaD`.`Instrument` (`idInstrument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adresseMembre`
    FOREIGN KEY (`fk_adresse`)
    REFERENCES `DBBagaD`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_typeMembres`
    FOREIGN KEY (`fk_groupe`)
    REFERENCES `DBBagaD`.`Groupe` (`idgroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`TypeEvenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`TypeEvenement` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`TypeEvenement` (
  `idType` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`ReferentExterieur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`ReferentExterieur` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`ReferentExterieur` (
  `idreferentExterieur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(20) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idreferentExterieur`, `mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`Evenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`Evenement` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`Evenement` (
  `idEvenement` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `dateDebut` DATETIME NOT NULL,
  `dateFin` DATETIME NOT NULL,
  `cachet` FLOAT NULL,
  `description` MEDIUMTEXT NULL,
  `image` VARCHAR(255) NULL,
  `valider` TINYINT NOT NULL,
  `fk_adresse` INT NOT NULL,
  `fk_type` INT NOT NULL,
  `fk_membre` INT NOT NULL,
  `fk_referentExterieur` INT NULL,
  PRIMARY KEY (`idEvenement`),
  INDEX `fk_adresseEvenement_idx` (`fk_adresse` ASC),
  INDEX `fk_typeEvenement_idx` (`fk_type` ASC),
  INDEX `fk_referentExterieur_idx` (`fk_referentExterieur` ASC),
  INDEX `fk_membre_idx` (`fk_membre` ASC),
  CONSTRAINT `fk_adresseEvenement`
    FOREIGN KEY (`fk_adresse`)
    REFERENCES `DBBagaD`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_typeEvenement`
    FOREIGN KEY (`fk_type`)
    REFERENCES `DBBagaD`.`TypeEvenement` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_referentExterieurEvenement`
    FOREIGN KEY (`fk_referentExterieur`)
    REFERENCES `DBBagaD`.`ReferentExterieur` (`idreferentExterieur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_membreEvenement`
    FOREIGN KEY (`fk_membre`)
    REFERENCES `DBBagaD`.`Membre` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`Reponse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`Reponse` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`Reponse` (
  `idReponse` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`idReponse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`Participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`Participant` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`Participant` (
  `fk_reponce` INT NOT NULL,
  `fk_membre` INT NOT NULL,
  `fk_evenement` INT NOT NULL,
  INDEX `fk_membresParticipant_idx` (`fk_membre` ASC),
  INDEX `fk_evenementParticipant_idx` (`fk_evenement` ASC),
  INDEX `fk_reponceParticipant_idx` (`fk_reponce` ASC),
  CONSTRAINT `fk_membresParticipant`
    FOREIGN KEY (`fk_membre`)
    REFERENCES `DBBagaD`.`Membre` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evenementParticipant`
    FOREIGN KEY (`fk_evenement`)
    REFERENCES `DBBagaD`.`Evenement` (`idEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponceParticipant`
    FOREIGN KEY (`fk_reponce`)
    REFERENCES `DBBagaD`.`Reponse` (`idReponse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`EmploiDuTemps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`EmploiDuTemps` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`EmploiDuTemps` (
  `idEmploiDuTemps` INT NOT NULL AUTO_INCREMENT,
  `EmploiDuTempscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmploiDuTemps`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`Role` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`GroupeRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`GroupeRole` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`GroupeRole` (
  `fk_groupe` INT NOT NULL,
  `fk_role` INT NOT NULL,
  INDEX `fk_groupe_idx` (`fk_groupe` ASC),
  INDEX `fk_role_idx` (`fk_role` ASC),
  CONSTRAINT `fk_groupeGR`
    FOREIGN KEY (`fk_groupe`)
    REFERENCES `DBBagaD`.`Groupe` (`idgroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roleGR`
    FOREIGN KEY (`fk_role`)
    REFERENCES `DBBagaD`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`Actualite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`Actualite` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`Actualite` (
  `idActualite` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `image` VARCHAR(255) NULL,
  `description` MEDIUMTEXT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT ,
  `fk_membre` INT NOT NULL,
  PRIMARY KEY (`idActualite`),
  INDEX `fk_membre_idx` (`fk_membre` ASC),
  CONSTRAINT `fk_membreActu`
    FOREIGN KEY (`fk_membre`)
    REFERENCES `DBBagaD`.`Membre` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBagaD`.`MembreRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBagaD`.`MembreRole` ;

CREATE TABLE IF NOT EXISTS `DBBagaD`.`MembreRole` (
  `fk_membre` INT NOT NULL,
  `fk_role` INT NOT NULL,
  INDEX `fk_membre_idx` (`fk_membre` ASC),
  INDEX `fk_Role_idx` (`fk_role` ASC),
  CONSTRAINT `fk_membreMR`
    FOREIGN KEY (`fk_membre`)
    REFERENCES `DBBagaD`.`Membre` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RoleMR`
    FOREIGN KEY (`fk_role`)
    REFERENCES `DBBagaD`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
